project_id = "daghobrbxgkgmflkcnyh"

[functions.therapist-access]
verify_jwt = false

[functions.request-therapist-reset]
verify_jwt = false

[functions.verify-therapist-reset]
verify_jwt = false

[functions.generate-daily-plans]
verify_jwt = false

[functions.admin-access]
verify_jwt = false
